modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="generated_mod"
version="1.0.0-r11"
displayName="团队死斗"
authors="AutoMods"
description='''团队死斗'''
[[dependencies.generated_mod]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.generated_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
